package tui

import (
	"strings"
	"sync"

	"charm.land/glamour/v2"
	glamouransi "charm.land/glamour/v2/ansi"
)

type markdownCacheEntry struct {
	text     string
	width    int
	rendered string
}

// markdownRenderer owns a small frontend-only cache. The activity model keeps
// canonical plain text, matching Python; Markdown is presentation state and is
// recomputed when either the authoritative final text or terminal width changes.
type markdownRenderer struct {
	mu      sync.Mutex
	entries map[string]markdownCacheEntry
	limit   int
}

func newMarkdownRenderer(limit int) *markdownRenderer {
	if limit < 1 {
		limit = 1
	}
	return &markdownRenderer{entries: make(map[string]markdownCacheEntry), limit: limit}
}

func (r *markdownRenderer) render(key, text string, width int) string {
	if r == nil {
		return text
	}
	if width < 1 {
		width = 1
	}
	r.mu.Lock()
	defer r.mu.Unlock()
	if cached, ok := r.entries[key]; ok && cached.text == text && cached.width == width {
		return cached.rendered
	}
	rendered, err := renderMarkdown(text, width)
	if err != nil {
		// Safe plain text is always an acceptable presentation fallback. A
		// renderer failure must not control or terminate the experiment.
		rendered = text
	}
	if _, exists := r.entries[key]; !exists && len(r.entries) >= r.limit {
		clear(r.entries)
	}
	r.entries[key] = markdownCacheEntry{text: text, width: width, rendered: rendered}
	return rendered
}

func renderMarkdown(text string, width int) (string, error) {
	style := markdownStyle()
	// Rich's hyperlinks=False renders a visible destination rather than an
	// OSC-8 terminal hyperlink. Glamour already emits plain link destinations;
	// these delimiters preserve the reference presentation: label (URL).
	style.Link.Prefix = "("
	style.Link.Suffix = ")"
	renderer, err := glamour.NewTermRenderer(
		glamour.WithStyles(style),
		glamour.WithWordWrap(width),
		glamour.WithInlineTableLinks(true),
	)
	if err != nil {
		return "", err
	}
	rendered, err := renderer.Render(text)
	if err != nil {
		return "", err
	}
	return strings.Trim(stripOSCSequences(rendered), "\n"), nil
}

func markdownStyle() glamouransi.StyleConfig {
	zero := uint(0)
	one := uint(1)
	bold := true
	italic := true
	crossedOut := true
	underline := true
	blockquoteToken := "│ "
	centerSeparator := "─"
	columnSeparator := "│"
	rowSeparator := "─"
	return glamouransi.StyleConfig{
		Document: glamouransi.StyleBlock{Margin: &zero},
		BlockQuote: glamouransi.StyleBlock{
			Indent: &one, IndentToken: &blockquoteToken,
		},
		List:           glamouransi.StyleList{LevelIndent: 2},
		Heading:        glamouransi.StyleBlock{StylePrimitive: glamouransi.StylePrimitive{Bold: &bold, BlockSuffix: "\n"}},
		Emph:           glamouransi.StylePrimitive{Italic: &italic},
		Strong:         glamouransi.StylePrimitive{Bold: &bold},
		Strikethrough:  glamouransi.StylePrimitive{CrossedOut: &crossedOut},
		HorizontalRule: glamouransi.StylePrimitive{Format: "\n────────\n"},
		Item:           glamouransi.StylePrimitive{BlockPrefix: "• "},
		Enumeration:    glamouransi.StylePrimitive{BlockPrefix: ". "},
		Task:           glamouransi.StyleTask{Ticked: "[✓] ", Unticked: "[ ] "},
		Link: glamouransi.StylePrimitive{
			Prefix: "(", Suffix: ")", Underline: &underline,
		},
		LinkText: glamouransi.StylePrimitive{Bold: &bold},
		Code: glamouransi.StyleBlock{StylePrimitive: glamouransi.StylePrimitive{
			Prefix: " ", Suffix: " ", Bold: &bold,
		}},
		CodeBlock: glamouransi.StyleCodeBlock{StyleBlock: glamouransi.StyleBlock{Margin: &zero}},
		Table: glamouransi.StyleTable{
			CenterSeparator: &centerSeparator,
			ColumnSeparator: &columnSeparator,
			RowSeparator:    &rowSeparator,
		},
	}
}

// Glamour v2 emits OSC-8 hyperlinks by default. The Python reference disables
// them and displays the destination as ordinary text. Strip only OSC sequences
// generated by the renderer while preserving trusted SGR presentation styles.
func stripOSCSequences(value string) string {
	var output strings.Builder
	for index := 0; index < len(value); {
		start := index
		switch {
		case value[index] == '\x9d':
			index++
		case value[index] == '\x1b' && index+1 < len(value) && value[index+1] == ']':
			index += 2
		default:
			output.WriteByte(value[index])
			index++
			continue
		}
		terminated := false
		for index < len(value) {
			switch {
			case value[index] == '\a' || value[index] == '\x9c':
				index++
				terminated = true
			case value[index] == '\x1b' && index+1 < len(value) && value[index+1] == '\\':
				index += 2
				terminated = true
			default:
				index++
			}
			if terminated {
				break
			}
		}
		if !terminated {
			// Glamour emits complete OSC sequences. Preserve an unexpected
			// incomplete suffix as visible text rather than silently dropping it.
			output.WriteString(value[start:])
			break
		}
	}
	return output.String()
}

func indentBlock(text string, prefix string) string {
	if text == "" {
		return ""
	}
	return prefix + strings.ReplaceAll(text, "\n", "\n"+prefix)
}
