#include "protocol.h"
#include "serial.h"
#include "tools.h"
typedef unsigned char u8;typedef unsigned short u16;typedef unsigned u32;typedef unsigned long u64;
#define FRAME_HEADER_SIZE 16u
#define FRAME_PROTOCOL_VERSION 1u
#define FINISH_GENERATION_INVOCATION_OVERHEAD 25u
#define FEATURE_REQUEST_INVOCATION_OVERHEAD 27u
#define REQUEST_BUFFER_SIZE \
(16u*1024u+256u+FEATURE_REQUEST_INVOCATION_OVERHEAD)
static u16 read_u16_le(const u8*bytes){return(u16)bytes[0]|((u16)bytes[1]<<8);}static u32 read_u32_le(const u8*bytes){return(u32)bytes[0]|((u32)bytes[1]<<8)|((u32)bytes[2]<<16)|((u32)bytes[3]<<24);}static void write_u16_le(u8*bytes,u16 value){bytes[0]=(u8)value;bytes[1]=(u8)(value>>8);}static void write_u32_le(u8*bytes,u32 value){bytes[0]=(u8)value;bytes[1]=(u8)(value>>8);bytes[2]=(u8)(value>>16);bytes[3]=(u8)(value>>24);}static void discard_bytes(u32 count){for(u32 index=0;index<count;++index){(void)serial_read();}}void frame_send_header(u16 message_type,u32 request_id,u32 payload_length){u8 header[FRAME_HEADER_SIZE];header[0]='C';header[1]='X';header[2]='O';header[3]='S';write_u16_le(header+4,FRAME_PROTOCOL_VERSION);write_u16_le(header+6,message_type);write_u32_le(header+8,request_id);write_u32_le(header+12,payload_length);serial_write_bytes(header,sizeof(header));}void frame_write_u16(u16 value){u8 bytes[2];write_u16_le(bytes,value);serial_write_bytes(bytes,sizeof(bytes));}void frame_write_u32(u32 value){u8 bytes[4];write_u32_le(bytes,value);serial_write_bytes(bytes,sizeof(bytes));}__attribute__((noreturn))void protocol_loop(void){u8 header[FRAME_HEADER_SIZE];u8 payload[REQUEST_BUFFER_SIZE];for(;;){for(u32 index=0;index<sizeof(header);++index){header[index]=serial_read();}u16 version=read_u16_le(header+4);u16 message_type=read_u16_le(header+6);u32 request_id=read_u32_le(header+8);u32 payload_length=read_u32_le(header+12);if(payload_length>FRAME_MAX_PAYLOAD){for(;;){__asm__ volatile("pause");}}int valid_header=header[0]=='C'&&header[1]=='X'&&header[2]=='O'&&header[3]=='S'&&version==FRAME_PROTOCOL_VERSION;if(payload_length>sizeof(payload)){discard_bytes(payload_length);if(valid_header&&message_type==INVOKE_TOOL_REQUEST&&request_id!=0){tools_send_failure(request_id);}continue;}for(u32 index=0;index<payload_length;++index){payload[index]=serial_read();}if(!valid_header||request_id==0){continue;}if(message_type==LIST_TOOLS_REQUEST&&payload_length==0){tools_send_list(request_id);}else if(message_type==INVOKE_TOOL_REQUEST){tools_handle_invocation(request_id,payload,payload_length);}}}
